name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: nuget/setup-nuget@v2

      - run: nuget restore src/CrowdedMod.sln

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - uses: microsoft/setup-msbuild@v2

      - run: msbuild src/CrowdedMod.sln -t:restore,rebuild -p:Configuration=Release -p:RestorePackagesConfig=true

      - uses: actions/upload-artifact@v4
        with:
          name: CrowdedMod.dll
          path: src/CrowdedMod/bin/Release/net6.0/CrowdedMod.dll